# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('queueType', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RankInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=10)),
                ('prevSeasonTier', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('summonerId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='rankinfo',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eloPurgatory.Summoner'),
        ),
    ]
